# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: YounSoo Park
title: A new Back-end Web Developer
email: ppsoo312@gmail.com
website: https://github.com/ppsoo312

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: ppsoo312

# About Section
# about_title: About Me
about_profile_image: images/ParkYounSoo.jpg
about_content: | # this will include new lines to allow paragraphs
  **More sincere than anyone else**
  

  누구보다 성실하게 한명의 개발자로 나아가고 싶은 <mark>박윤수</mark> 라고 합니다!
  
  개발자로 진로를 정한 이후에 쳐지지 않기 위해 쉬지 않고 달려왔습니다. 
  
  계속해서 성장과 발전을 하기 위해 끊임없이 노력할 것입니다.
  
content:
  - title: Myongji College # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Myongji College
        link: http://naver.me/5vYwJD7N
        # link_text: 성적증명서
        quote: >
          Myongji College 소프트웨어콘텐츠학과 졸업
        description: | # this will include new lines to allow paragraphs
                                                               전공<br />
                                                               
                                          웹프로그래밍(2018-1학기)         프로그래밍기초(2018-1학기) <br />
                                          앱프로그래밍(2018-1학기)         게임개발기초(2018-1학기) <br />
                                          서버프로그래밍기초(2018-2학기)    앱개발기초(2018-2학기) <br />
                                          네트워크게임(2018-2학기)         게임개발응용(2018-2학기) <br />
                                          앱개발응용(2019-1학기)           게임인공지능(2019-1학기) <br />
                                          가상현실게임(2019-1학기)         콘텐츠기획(2019-1학기) <br />
                                          게임개발실무(2019-2학기)         앱개발실무(2019-2학기) <br />
                                          가상현실그래픽실습(2019-2학기)
  - title: 국비과정 교육 수료 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: (디지털컨버전스) 디지털데이터 융합 자바기반 풀스택 개발자 양성 과정A
        link: http://naver.me/5Af2I3DC
        # link_text: 수료증
        quote: >
          더 많은 것을 배워보고싶고, 여러 경험과 다른 사람과의 프로젝트를 함께 해보고 싶어 국비과정을 수료하게되었습니다.
        description: | # this will include new lines to allow paragraphs
                            국비과정을 통해 개발자로써 필요한 부분을 배워 발전할 수 있는 계기가 되었고,
          
                            여러사람들과의 프로젝트를 통해 한층 더 개발자라는 직업에 매력을 느끼게 되었습니다.
  - title: 프로젝트 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Hidden Gosu
        link: github.com/somizoo/uswaytrip
        # link_text: Project Website
        additional_links:
          - title: 프로젝트 및 시연 ppt
            icon: fab fa-github
            url: https://prezi.com/view/ZAfCTLpkjsxnW6vRLlYt/
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          국비 과정에서 만들었던 프로젝트입니다. 링크를 통해 프로젝트 및 박윤수 시연 ppt를 확인할 수 있습니다.
        description: | # this will include new lines to allow paragraphs
          프로젝트를 진행하면서 여러사람과의 협업 즉 <mark>팀워크</mark>가 얼마나 중요한지 느껴보는 시간이었습니다.
          
          팀원이 부족한 부분은 제가 채워나가고 제가 부족한 부분은 팀원이 채워나가며 프로젝트를 완성했을 때 얼마나 <mark>값진 경험</mark>인지 느끼고 발전하는 시간이었습니다.
  - title: 입사지원서 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 입사지원서
        link: http://naver.me/5HE4FeiF
        # link_text: 입사지원서
        quote: >
          신입 개발자로써 성실함과 꾸준함 얼마나 배우고자하여 성장하는지 중요하다고 생각합니다. 사회에 나온지 긴 시간은 아니지만 그 시간동안 꾸준히 목표를 향해 달려왔습니다.
        description: | # this will include new lines to allow paragraphs
                   국비 과정에서 JAVA, JSP, SPRING, HTML, CSS 등을 공부하였고, 팀원들과 함께 프로젝트를 진행한 바 있습니다.
          
                   프로젝트에서 맡았던 역할 등은 <mark>입사지원서</mark>를 참고해주시기 바랍니다.
  - title: 자격증 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: 자격증
        link: http://naver.me/xD6FA3su
        # link_text: 자격증
        quote: >
          현업과 관련된 자격증을 취득하였고, 관련된 다른 자격증 취득도 목표로 하고 있습니다.
        description: | # this will include new lines to allow paragraphs
                     정보처리산업기사 (2021.11.26)

                     운전면허 1종보통(2019.07.31)                                    
  - title: 구현가능한 기능 # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 구현가능한 기능
        quote: >
         구현할 수 있는 기능과 프로젝트를 진행하며 구현했던 기능들 나열
        description: | # this will include new lines to allow paragraphs
         - 정보처리산업기사
         - 회원관련(로그인, 회원가입, 삭제, 변경 등) CRUD
          - Session 을 이용한 로그인 처리 및 정보 샤용(아이디 기억하기, 세션을 활용한 로그인 정보 넘겨서 다른 부분에서 처리)
         - 매칭시스템CRUD - Higo Project 참조
          - 매칭시스템(1:1, 1:N) 기능 구현
          - 카테고리별(대, 중, 소), 질문 타입별(단일형, 다중형, 서술형) 답변처리
          - 데이터베이스 비교(회원 데이터베이스, 고수회원 데이터베이스)를 통한 매칭
          - 캐시(기본 캐시, 서비스 캐시 처리 순서 로직)
          - (게시판CRUD)견적요청서를 기반으로한 견적서 처리(자주쓰는 데이터 저장 및 불러오기, 게시판 커스터마이징)
         - JSTL을 이용한 기능 구축
         - ArrayList, Map을 통한 데이터 처리
         - HIGO Project에서 디버깅(회원 관련 디버깅, 캐시 관련 디버깅, 매칭 관련 디버깅)
         - 캐시 시스템(캐시 충전(+), 견적서 전달(-))
         - 게시판 CRUD 구현
         - 상속을 이용한 회원 구현
         - 요구 명세서 기반 데이터베이스 설계
         - 데이터베이스 xml을 이용하여 검색, 삽입, 변경, 삭제 가능
         - ORACLE을 이용한 데이터베이스 설계 및 구현
         - html, css 활용가능, js를 통한 유효성 검사
         - SQL Developer, DBeaver, Oracle 사용 데이터베이스 관리
         - 가능
# Footer
footer_show_references: true
# references_title: Nice to meet you (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
